version: 0.1.6
name: realtimekit_core
description: Realtimekit Core SDK
homepage: https://docs.realtime.cloudflare.com/flutter-core

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: realtimekit_core_android
      ios:
        default_package: realtimekit_core_ios
  assets:
    - pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  pubspec_parse: ^1.5.0
  realtimekit_core_ios: ^0.1.4
  realtimekit_core_android: ^0.1.6
  realtimekit_core_platform_interface: ^0.1.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  plugin_platform_interface: ^2.1.8
